import Navbar from "@/components/Navbar"

export const metadata = {
  title: 'Rafay Nadeem Portfolio',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <div className="h-screen w-screen border-l-indigo-700">
        <Navbar />
        {children}
        </div>
        </body>
    </html>
  )
}
